# 테이블 생성
drop table if exists item CASCADE;
create table item
(
    id        bigint generated by default as identity,
    item_name varchar(10),
    price     integer,
    quantity  integer,
    primary key (id)
);
# generated by default as identity : identity 전략이라고 하는데, 기본 키 생성을 데이터베이스에 위임하는 방법이다.( == MySQL의 Auto Increment)


# 테스트 등록 쿼리
insert into item(item_name, price, quantity) values ('ItemTest', 10000, 10);